### ISSUE TITLE
Update Google Analytics tag

### ISSUE THREAD

**Issue by pschwllr** [asarigun/asarigun.github.io#1]
Hi, I'm glad that you used my adapted template for your personal webpage (if you want, you could add a pointer in the readme), but what would be awesome is if you updated the google analytics tag. So, it does not get tracked on mine. 

Thanks!

https://github.com/asarigun/asarigun.github.io/blob/d2000106587ae809c290405c4b063eabaa347c5d/index.html#L16

Best wishes,

Philippe

**Comment by asarigun** [comment]
Hi, thank you for your template and information about `tagmanager ID`. I just updated google tag manager. I hope the same issue will not happen again. I would be very grateful if you informed me if the same issue happens again.

Best wishes,
Ahmet
